"""
Arithmetic Operations

This module contains mappings for:
- Basic arithmetic (ADD, SUB, MUL, DIV, MOD)
- Division with variants (DIVMOD, MULDIV, etc.)
- Comparison operations
- Bitwise/Logical operations

See arithmetic_quiet.py for quiet (Q*) arithmetic operations.
See arithmetic_shift.py for shift operations.
"""

from ..ir_types import IRType

ARITHMETIC_BASIC_MAPPINGS = {
    # ========== Arithmetic - Basic ==========
    "ADD": IRType.ARITHMETIC,
    "SUB": IRType.ARITHMETIC,
    "SUBR": IRType.ARITHMETIC,
    "MUL": IRType.ARITHMETIC,
    "INC": IRType.ARITHMETIC,
    "DEC": IRType.ARITHMETIC,
    "ADDCONST": IRType.ARITHMETIC,
    "MULCONST": IRType.ARITHMETIC,
    "NEGATE": IRType.ARITHMETIC_NEGATE,
    "NEG": IRType.ARITHMETIC_NEGATE,
    "ABS": IRType.ARITHMETIC_NEGATE,

    # Arithmetic - Division
    "DIV": IRType.ARITHMETIC_DIV,
    "MOD": IRType.ARITHMETIC_DIV,
    "DIVMOD": IRType.ARITHMETIC_DIV,
    "DIVC": IRType.ARITHMETIC_DIV,
    "MODC": IRType.ARITHMETIC_DIV,
    "DIVMODC": IRType.ARITHMETIC_DIV,
    "DIVR": IRType.ARITHMETIC_DIV,
    "MODPOW2": IRType.ARITHMETIC_DIV,
    "RSHIFTR": IRType.ARITHMETIC_SHIFT,
    "RSHIFTC": IRType.ARITHMETIC_SHIFT,

    # Arithmetic - Shifts
    "LSHIFT": IRType.ARITHMETIC_SHIFT,
    "RSHIFT": IRType.ARITHMETIC_SHIFT,
    "PUSHPOW2": IRType.ARITHMETIC_SHIFT,

    # Arithmetic - Quiet (no exceptions on overflow)
    "QADD": IRType.ARITHMETIC_QUIET,
    "QSUB": IRType.ARITHMETIC_QUIET,
    "QMUL": IRType.ARITHMETIC_QUIET,
    "QMULINT": IRType.ARITHMETIC_QUIET,
    "QINC": IRType.ARITHMETIC_QUIET,
    "QDEC": IRType.ARITHMETIC_QUIET,

    # Misc Arithmetic
    "ADDINT": IRType.ARITHMETIC,
    "MULINT": IRType.ARITHMETIC,
    "SUBINT": IRType.ARITHMETIC,
    "NEGPOW2": IRType.ARITHMETIC,
    "POW2": IRType.ARITHMETIC,
    "BITSIZE": IRType.ARITHMETIC,
    "ADDRAND": IRType.ARITHMETIC,
    "RAND": IRType.ARITHMETIC,
    "RANDU256": IRType.ARITHMETIC,

    # Fit/Size Operations
    "FITS": IRType.ARITHMETIC,
    "FITSX": IRType.ARITHMETIC,
    "UFITS": IRType.ARITHMETIC,
    "UFITSX": IRType.ARITHMETIC,
    "MIN": IRType.ARITHMETIC,
    "QMIN": IRType.ARITHMETIC,
}

ARITHMETIC_DIV_MAPPINGS = {
    # ========== Arithmetic Division Operations ==========
    "DIVMOD": IRType.DIV_MOD,
    "DIVMODR": IRType.DIV_MOD,
    "DIVMODC": IRType.DIV_MOD,
    "RSHIFTR": IRType.MOD_ROUND,
    "RSHIFTC": IRType.MOD_ROUND,
    "MODR": IRType.MOD_ROUND,
    "MODC": IRType.MOD_ROUND,
    "MODPOW2R": IRType.MOD_ROUND,
    "MODPOW2C": IRType.MOD_ROUND,
    "MULDIV": IRType.MUL_DIV,
    "MULDIVR": IRType.MUL_DIV,
    "MULDIVC": IRType.MUL_DIV,
    "MULRSHIFT": IRType.MUL_DIV,
    "MULRSHIFTR": IRType.MUL_DIV,
    "MULRSHIFTC": IRType.MUL_DIV,
    "MULMODPOW2": IRType.MUL_MOD,
    "MULMODPOW2R": IRType.MUL_MOD,
    "MULMODPOW2C": IRType.MUL_MOD,
    "MULMODPOW2_": IRType.MUL_MOD,
    "MULMODPOW2R_": IRType.MUL_MOD,
    "MULMODPOW2C_": IRType.MUL_MOD,
    "MULMOD": IRType.MUL_MOD,
    "MULMODR": IRType.MUL_MOD,
    "MULMODC": IRType.MUL_MOD,
    "ADDDIVMOD": IRType.ADD_DIV_MOD,
    "ADDDIVMODR": IRType.ADD_DIV_MOD,
    "ADDDIVMODC": IRType.ADD_DIV_MOD,
    "ADDRSHIFTMOD": IRType.ADD_DIV_MOD,
    "ADDRSHIFTMODR": IRType.ADD_DIV_MOD,
    "ADDRSHIFTMODC": IRType.ADD_DIV_MOD,
    "ADDMODPOW2": IRType.ADD_DIV_MOD,
    "ADDMODPOW2R": IRType.ADD_DIV_MOD,
    "ADDMODPOW2C": IRType.ADD_DIV_MOD,
    # More division variants
    "LSHIFTDIV": IRType.MUL_DIV,
    "LSHIFTDIVR": IRType.MUL_DIV,
    "LSHIFTDIVC": IRType.MUL_DIV,
    "LSHIFTMOD": IRType.MUL_MOD,
    "LSHIFTMODR": IRType.MUL_MOD,
    "LSHIFTMODC": IRType.MUL_MOD,
    # 256-bit variants
    "DIVMOD256": IRType.DIV_MOD,
    "DIVMOD256R": IRType.DIV_MOD,
    "DIVMOD256C": IRType.DIV_MOD,
    "RSHIFT256MOD": IRType.MOD_ROUND,
    "RSHIFT256MODR": IRType.MOD_ROUND,
    "RSHIFT256MODC": IRType.MOD_ROUND,
    "MULDIVMOD256": IRType.MUL_DIV,
    "MULDIVMOD256R": IRType.MUL_DIV,
    "MULDIVMOD256C": IRType.MUL_DIV,
    "MULRSHIFT256": IRType.MUL_DIV,
    "MULRSHIFT256R": IRType.MUL_DIV,
    "MULRSHIFT256C": IRType.MUL_DIV,
    "MULMODPOW2_256": IRType.MUL_MOD,
    "MULMODPOW2_256R": IRType.MUL_MOD,
    "MULMODPOW2_256C": IRType.MUL_MOD,
    "LSHIFT256DIV": IRType.MUL_DIV,
    "LSHIFT256DIVR": IRType.MUL_DIV,
    "LSHIFT256DIVC": IRType.MUL_DIV,
    "LSHIFT256MOD": IRType.MUL_MOD,
    "LSHIFT256MODR": IRType.MUL_MOD,
    "LSHIFT256MODC": IRType.MUL_MOD,
    # Additional division operations
    "MULDIVMOD": IRType.MUL_DIV,
    "MULDIVMODR": IRType.MUL_DIV,
    "MULDIVMODC": IRType.MUL_DIV,
    "MULRSHIFTMOD": IRType.MUL_DIV,
    "MULRSHIFTMODR": IRType.MUL_DIV,
    "MULRSHIFTMODC": IRType.MUL_DIV,
    "LSHIFTDIVMOD": IRType.MUL_DIV,
    "LSHIFTDIVMODR": IRType.MUL_DIV,
    "LSHIFTDIVMODC": IRType.MUL_DIV,
    "ADDMULDIVMOD": IRType.ADD_DIV_MOD,
    "ADDMULDIVMODR": IRType.ADD_DIV_MOD,
    "ADDMULDIVMODC": IRType.ADD_DIV_MOD,
    "ADDRSHIFT256MOD": IRType.ADD_DIV_MOD,
    "ADDRSHIFT256MODR": IRType.ADD_DIV_MOD,
    "ADDRSHIFT256MODC": IRType.ADD_DIV_MOD,
    "ADDLSHIFT256MOD": IRType.ADD_DIV_MOD,
    "ADDLSHIFT256MODR": IRType.ADD_DIV_MOD,
    "ADDLSHIFT256MODC": IRType.ADD_DIV_MOD,
    "ADDMULRSHIFT256MOD": IRType.ADD_DIV_MOD,
    "ADDMULRSHIFT256MODR": IRType.ADD_DIV_MOD,
    "ADDMULRSHIFT256MODC": IRType.ADD_DIV_MOD,
    "ADDMULMOD256": IRType.ADD_DIV_MOD,
    "ADDMULMOD256R": IRType.ADD_DIV_MOD,
    "ADDMULMOD256C": IRType.ADD_DIV_MOD,

    # Add/Mod/Div Operations
    "ADDRSHIFTC_MOD": IRType.ARITHMETIC_DIV,
    "ADDRSHIFTR_MOD": IRType.ARITHMETIC_DIV,
    "ADDRSHIFT_MOD": IRType.ARITHMETIC_DIV,
    "MODPOW2C_": IRType.ARITHMETIC_DIV,
    "MODPOW2R_": IRType.ARITHMETIC_DIV,
    "MODPOW2_": IRType.ARITHMETIC_DIV,
}

COMPARISON_MAPPINGS = {
    # ========== Comparison ==========
    "EQUAL": IRType.COMPARISON,
    "QEQUAL": IRType.COMPARISON,
    "EQINT": IRType.COMPARISON,
    "QEQINT": IRType.COMPARISON,
    "LESS": IRType.COMPARISON,
    "QLESS": IRType.COMPARISON,
    "LESSINT": IRType.COMPARISON,
    "QLESSINT": IRType.COMPARISON,
    "GREATER": IRType.COMPARISON,
    "QGREATER": IRType.COMPARISON,
    "GTINT": IRType.COMPARISON,
    "QGTINT": IRType.COMPARISON,
    "LEQ": IRType.COMPARISON,
    "QLEQ": IRType.COMPARISON,
    "GEQ": IRType.COMPARISON,
    "QGEQ": IRType.COMPARISON,
    "NEQ": IRType.COMPARISON,
    "QNEQ": IRType.COMPARISON,
    "NEQINT": IRType.COMPARISON,
    "QNEQINT": IRType.COMPARISON,
    "CMP": IRType.COMPARISON,
    "QCMP": IRType.COMPARISON,
    "MAX": IRType.COMPARISON,
    "QMAX": IRType.COMPARISON,
    "MINMAX": IRType.COMPARISON,
    "QMINMAX": IRType.COMPARISON,
    "SDLEXCMP": IRType.COMPARISON,
    "SDPFXREV": IRType.COMPARISON,
    "SDPPFXREV": IRType.COMPARISON,
    "SDPSFXREV": IRType.COMPARISON,
    "SDSFXREV": IRType.COMPARISON,

    "SGN": IRType.COMPARISON_SGN,
    "ISPOS": IRType.COMPARISON_SGN,
    "ISNEG": IRType.COMPARISON_SGN,
    "ISZERO": IRType.COMPARISON_SGN,
    "ISNAN": IRType.COMPARISON_SGN,
    "CHKNAN": IRType.COMPARISON_SGN,
    "ISNNEG": IRType.COMPARISON_SGN,
    "ISNPOS": IRType.COMPARISON_SGN,
    "ISNZERO": IRType.COMPARISON_SGN,
    "SGNINT": IRType.COMPARISON_SGN,

    # Comparison Operations (slice)
    "SDEQ": IRType.COMPARE_SLICE_EQ,
    "SDPFX": IRType.COMPARE_SLICE_PREFIX,
    "SDPPFX": IRType.COMPARE_SLICE_PREFIX,
    "SDSFX": IRType.COMPARE_SLICE_PREFIX,
    "SDPSFX": IRType.COMPARE_SLICE_PREFIX,
}

BITWISE_MAPPINGS = {
    # ========== Bitwise/Logical ==========
    "AND": IRType.BITWISE,
    "OR": IRType.BITWISE,
    "XOR": IRType.BITWISE,
    "NOT": IRType.BITWISE,
    "BOOLAND": IRType.BITWISE,
    "BOOLOR": IRType.BITWISE,
    "INVERT": IRType.BITWISE,
    "UBITSIZE": IRType.BITWISE,
    "QUBITSIZE": IRType.BITWISE,
}

# Import from separate files
from .arithmetic_quiet import ARITHMETIC_QUIET_MAPPINGS
from .arithmetic_shift import ARITHMETIC_SHIFT_MAPPINGS

# Combined arithmetic operations
ARITHMETIC_MAPPINGS = {
    **ARITHMETIC_BASIC_MAPPINGS,
    **ARITHMETIC_DIV_MAPPINGS,
    **ARITHMETIC_QUIET_MAPPINGS,
    **ARITHMETIC_SHIFT_MAPPINGS,
    **COMPARISON_MAPPINGS,
    **BITWISE_MAPPINGS,
}
