"""
Arithmetic Shift Operations

This module contains mappings for:
- Left shift operations (LSHIFT*)
- Right shift operations (RSHIFT*)
- Multiply operations with shifts (MUL*SHIFT*)
- Variable shift operations (*_VAR)
"""

from ..ir_types import IRType

ARITHMETIC_SHIFT_MAPPINGS = {
    # ========== Bitwise Shift Operations ==========
    "FITSX": IRType.BITWISE_SHIFT,
    "UFITSX": IRType.BITWISE_SHIFT,
    "LSHIFT_VAR": IRType.BITWISE_SHIFT,
    "RSHIFT_VAR": IRType.BITWISE_SHIFT,

    # ========== Multiply Operations (MUL*) ==========
    "MULADDDIVMOD": IRType.MUL_DIV,
    "MULADDDIVMODC": IRType.MUL_DIV,
    "MULADDDIVMODR": IRType.MUL_DIV,
    "MULADDRSHIFTCMOD": IRType.MUL_DIV,
    "MULADDRSHIFTC_MOD": IRType.MUL_DIV,
    "MULADDRSHIFTMOD": IRType.MUL_DIV,
    "MULADDRSHIFTRMOD": IRType.MUL_DIV,
    "MULADDRSHIFTR_MOD": IRType.MUL_DIV,
    "MULADDRSHIFT_MOD": IRType.MUL_DIV,
    "MULRSHIFTCMOD": IRType.MUL_DIV,
    "MULRSHIFTC_": IRType.MUL_DIV,
    "MULRSHIFTC_MOD": IRType.MUL_DIV,
    "MULRSHIFTRMOD": IRType.MUL_DIV,
    "MULRSHIFTR_": IRType.MUL_DIV,
    "MULRSHIFTR_MOD": IRType.MUL_DIV,
    "MULRSHIFT_": IRType.MUL_DIV,
    "MULRSHIFT_MOD": IRType.MUL_DIV,

    # ========== Left Shift Operations (LSHIFT*) ==========
    "LSHIFTADDDIVMOD": IRType.ARITHMETIC_SHIFT,
    "LSHIFTADDDIVMODC": IRType.ARITHMETIC_SHIFT,
    "LSHIFTADDDIVMODR": IRType.ARITHMETIC_SHIFT,
    "LSHIFT_ADDDIVMOD": IRType.ARITHMETIC_SHIFT,
    "LSHIFT_ADDDIVMODC": IRType.ARITHMETIC_SHIFT,
    "LSHIFT_ADDDIVMODR": IRType.ARITHMETIC_SHIFT,
    "LSHIFT_DIV": IRType.ARITHMETIC_SHIFT,
    "LSHIFT_DIVC": IRType.ARITHMETIC_SHIFT,
    "LSHIFT_DIVMOD": IRType.ARITHMETIC_SHIFT,
    "LSHIFT_DIVMODC": IRType.ARITHMETIC_SHIFT,
    "LSHIFT_DIVMODR": IRType.ARITHMETIC_SHIFT,
    "LSHIFT_DIVR": IRType.ARITHMETIC_SHIFT,
    "LSHIFT_MOD": IRType.ARITHMETIC_SHIFT,
    "LSHIFT_MODC": IRType.ARITHMETIC_SHIFT,
    "LSHIFT_MODR": IRType.ARITHMETIC_SHIFT,

    # ========== Right Shift Operations (RSHIFT*) ==========
    "RSHIFTC_": IRType.ARITHMETIC_SHIFT,
    "RSHIFTC_MOD": IRType.ARITHMETIC_SHIFT,
    "RSHIFTMOD": IRType.ARITHMETIC_SHIFT,
    "RSHIFTMODC": IRType.ARITHMETIC_SHIFT,
    "RSHIFTMODR": IRType.ARITHMETIC_SHIFT,
    "RSHIFTR_": IRType.ARITHMETIC_SHIFT,
    "RSHIFTR_MOD": IRType.ARITHMETIC_SHIFT,
    "RSHIFT_": IRType.ARITHMETIC_SHIFT,
    "RSHIFT_ALT": IRType.ARITHMETIC_SHIFT,
    "RSHIFT_MOD": IRType.ARITHMETIC_SHIFT,

    # Shift/Mod with Variable (cp0.json)
    "ADDRSHIFTCMOD": IRType.MUL_DIV,
    "ADDRSHIFTMOD_VAR": IRType.MUL_DIV,
    "ADDRSHIFTRMOD": IRType.MUL_DIV,
    "LSHIFTADDDIVMODC_VAR": IRType.MUL_DIV,
    "LSHIFTADDDIVMODR_VAR": IRType.MUL_DIV,
    "LSHIFTADDDIVMOD_VAR": IRType.MUL_DIV,
    "LSHIFTDIVC_VAR": IRType.MUL_DIV,
    "LSHIFTDIVMODC_VAR": IRType.MUL_DIV,
    "LSHIFTDIVMODR_VAR": IRType.MUL_DIV,
    "LSHIFTDIVMOD_VAR": IRType.MUL_DIV,
    "LSHIFTDIVR_VAR": IRType.MUL_DIV,
    "LSHIFTDIV_VAR": IRType.MUL_DIV,
    "LSHIFTMODC_VAR": IRType.ARITHMETIC_SHIFT,
    "LSHIFTMODR_VAR": IRType.ARITHMETIC_SHIFT,
    "LSHIFTMOD_VAR": IRType.ARITHMETIC_SHIFT,
    "MODPOW2C_VAR": IRType.ARITHMETIC_SHIFT,
    "MODPOW2R_VAR": IRType.ARITHMETIC_SHIFT,
    "MODPOW2_VAR": IRType.ARITHMETIC_SHIFT,
    "MULADDRSHIFTCMOD_VAR": IRType.MUL_DIV,
    "MULADDRSHIFTMOD_VAR": IRType.MUL_DIV,
    "MULADDRSHIFTRMOD_VAR": IRType.MUL_DIV,
    "MULMODPOW2C_VAR": IRType.MUL_MOD,
    "MULMODPOW2R_VAR": IRType.MUL_MOD,
    "MULMODPOW2_VAR": IRType.MUL_MOD,
    "MULRSHIFTCMOD_VAR": IRType.MUL_DIV,
    "MULRSHIFTC_VAR": IRType.MUL_DIV,
    "MULRSHIFTMOD_VAR": IRType.MUL_DIV,
    "MULRSHIFTRMOD_VAR": IRType.MUL_DIV,
    "MULRSHIFTR_VAR": IRType.MUL_DIV,
    "MULRSHIFT_VAR": IRType.MUL_DIV,
    "RSHIFTCMOD": IRType.ARITHMETIC_SHIFT,
    "RSHIFTC_VAR": IRType.ARITHMETIC_SHIFT,
    "RSHIFTMODC_VAR": IRType.ARITHMETIC_SHIFT,
    "RSHIFTMODR_VAR": IRType.ARITHMETIC_SHIFT,
    "RSHIFTMOD_VAR": IRType.ARITHMETIC_SHIFT,
    "RSHIFTRMOD": IRType.ARITHMETIC_SHIFT,
    "RSHIFTR_VAR": IRType.ARITHMETIC_SHIFT,
}
