"""
Control Flow Operations

This module contains mappings for:
- Call/Return operations
- Jumps (conditional and unconditional)
- Loops (REPEAT, UNTIL, WHILE, AGAIN)
- Continuation registers
- Exceptions (THROW, TRY)
"""

from ..ir_types import IRType

CONTROL_FLOW_MAPPINGS = {
    # ========== Control Flow - Basic ==========
    "CALL": IRType.CALL,
    "CALLREF": IRType.CALL,
    "CALLXARGS": IRType.CALL,
    "CALLXARGS_VAR": IRType.CALL,
    "CALLXVARARGS": IRType.CALL,
    "CALLCCARGS": IRType.CALL,
    "CALLCCVARARGS": IRType.CALL,

    "EXECUTE": IRType.CALL_INDIRECT,
    "JMPX": IRType.UNCONDITIONAL_JUMP,
    "CALLCC": IRType.CALL_INDIRECT,
    "BOOLEVAL": IRType.CALL_INDIRECT,

    "RET": IRType.RETURN,
    "RETALT": IRType.RETURN,
    "RETARGS": IRType.RETURN,
    "RETVARARGS": IRType.RETURN,
    "RETDATA": IRType.RETURN,

    "JMP": IRType.UNCONDITIONAL_JUMP,
    "JMPREF": IRType.UNCONDITIONAL_JUMP,
    "JMPREFDATA": IRType.UNCONDITIONAL_JUMP,
    "JMPXDATA": IRType.UNCONDITIONAL_JUMP,
    "JMPXARGS": IRType.UNCONDITIONAL_JUMP,
    "JMPXVARARGS": IRType.UNCONDITIONAL_JUMP,
    "BRANCH": IRType.UNCONDITIONAL_JUMP,

    # ========== Control Flow - Conditional ==========
    "IF": IRType.CONDITIONAL_BRANCH,
    "IFNOT": IRType.CONDITIONAL_BRANCH,
    "IFELSE": IRType.CONDITIONAL_BRANCH,
    "IFREF": IRType.CONDITIONAL_BRANCH,
    "IFNOTREF": IRType.CONDITIONAL_BRANCH,
    "IFREFELSE": IRType.CONDITIONAL_BRANCH,
    "IFELSEREF": IRType.CONDITIONAL_BRANCH,
    "IFREFELSEREF": IRType.CONDITIONAL_BRANCH,

    "IFJMP": IRType.CONDITIONAL_JUMP,
    "IFNOTJMP": IRType.CONDITIONAL_JUMP,
    "IFJMPREF": IRType.CONDITIONAL_JUMP,
    "IFNOTJMPREF": IRType.CONDITIONAL_JUMP,

    "IFRET": IRType.CONDITIONAL_RETURN,
    "IFNOTRET": IRType.CONDITIONAL_RETURN,
    "IFRETALT": IRType.CONDITIONAL_RETURN,
    "IFNOTRETALT": IRType.CONDITIONAL_RETURN,

    "CONDSEL": IRType.SELECT_CONDITIONAL,
    "CONDSELCHK": IRType.SELECT_CONDITIONAL,

    "IFBITJMP": IRType.BIT_CONDITIONAL_JUMP,
    "IFNBITJMP": IRType.BIT_CONDITIONAL_JUMP,
    "IFBITJMPREF": IRType.BIT_CONDITIONAL_JUMP,
    "IFNBITJMPREF": IRType.BIT_CONDITIONAL_JUMP,

    # ========== Control Flow - Loops ==========
    "REPEAT": IRType.LOOP_REPEAT,
    "REPEATEND": IRType.LOOP_REPEAT,
    "REPEATBRK": IRType.LOOP_REPEAT,
    "REPEATENDBRK": IRType.LOOP_REPEAT,

    "UNTIL": IRType.LOOP_UNTIL,
    "UNTILEND": IRType.LOOP_UNTIL,
    "UNTILBRK": IRType.LOOP_UNTIL,
    "UNTILENDBRK": IRType.LOOP_UNTIL,

    "WHILE": IRType.LOOP_WHILE,
    "WHILEEND": IRType.LOOP_WHILE,
    "WHILEBRK": IRType.LOOP_WHILE,
    "WHILEENDBRK": IRType.LOOP_WHILE,

    "AGAIN": IRType.LOOP_AGAIN,
    "AGAINEND": IRType.LOOP_AGAIN,
    "AGAINBRK": IRType.LOOP_AGAIN,
    "AGAINENDBRK": IRType.LOOP_AGAIN,

    # ========== Control Flow - Continuation Registers ==========
    "PUSHCONT": IRType.PUSH_CONTINUATION,
    "PUSHCONT_SHORT": IRType.PUSH_CONTINUATION,
    "PUSHCONT_LONG": IRType.PUSH_CONTINUATION,
    "PUSHCTR": IRType.PUSH_CONTINUATION,
    "PUSHCTRX": IRType.PUSH_CONTINUATION,

    "POPCTR": IRType.POP_CONTINUATION,
    "POPCTRX": IRType.POP_CONTINUATION,

    "SETCONTCTR": IRType.SET_CONTINUATION,
    "SETRETCTR": IRType.SET_CONTINUATION,
    "SETALTCTR": IRType.SET_CONTINUATION,
    "SETCONTARGS": IRType.SET_CONTINUATION,
    "SETCONTCTRX": IRType.SET_CONTINUATION,

    "SAVE": IRType.SAVE_CONTINUATION,
    "SAVECTR": IRType.SAVE_CONTINUATION,
    "SAVEALT": IRType.SAVE_CONTINUATION,
    "SAVEALTCTR": IRType.SAVE_CONTINUATION,
    "SAVEBOTH": IRType.SAVE_CONTINUATION,
    "SAVEBOTHCTR": IRType.SAVE_CONTINUATION,
    "POPSAVE": IRType.SAVE_CONTINUATION,
    "COMPOS": IRType.SAVE_CONTINUATION,
    "COMPOSALT": IRType.SAVE_CONTINUATION,
    "COMPOSBOTH": IRType.SAVE_CONTINUATION,

    # ========== Exceptions ==========
    "THROW": IRType.THROW,
    "THROW_SHORT": IRType.THROW,
    "THROWARG": IRType.THROW,
    "THROWANY": IRType.THROW_ANY,
    "THROWARGANY": IRType.THROW_ANY,

    "THROWIF": IRType.THROW_IF,
    "THROWIF_SHORT": IRType.THROW_IF,
    "THROWARGIF": IRType.THROW_IF,
    "THROWANYIF": IRType.THROW_ANY,
    "THROWARGANYIF": IRType.THROW_ANY,

    "THROWIFNOT": IRType.THROW_IF_NOT,
    "THROWIFNOT_SHORT": IRType.THROW_IF_NOT,
    "THROWARGIFNOT": IRType.THROW_IF_NOT,
    "THROWANYIFNOT": IRType.THROW_ANY,
    "THROWARGANYIFNOT": IRType.THROW_ANY,

    "TRY": IRType.TRY_CATCH,
    "TRYARGS": IRType.TRY_CATCH,

    # Return/Control Flow variants
    "RETBOOL": IRType.RETURN,
    "RETURNARGS": IRType.SET_CONTINUATION,
    "RETURNVARARGS": IRType.SET_CONTINUATION,
    "THENRET": IRType.SET_CONTINUATION,
    "THENRETALT": IRType.SET_CONTINUATION,

    # Continuation Operations
    "BLESS": IRType.PUSH_CONT,
    "BLESSARGS": IRType.PUSH_CONT,
    "BLESSVARARGS": IRType.PUSH_CONT,
    "ATEXIT": IRType.SET_CONTINUATION,
    "ATEXITALT": IRType.SET_CONTINUATION,

    # cont_basic - VM execution
    "RUNVM": IRType.CALL_INDIRECT,
    "RUNVMX": IRType.CALL_INDIRECT,

    # cont_dict - Dictionary jumps
    "JMPDICT": IRType.UNCONDITIONAL_JUMP,
    "PREPAREDICT": IRType.DICT_GET,

    # cont_registers - Continuation registers
    "SAMEALT": IRType.SET_CONTINUATION,
    "SAMEALTSAVE": IRType.SET_CONTINUATION,
    "SETCONTCTRMANY": IRType.SET_CONTINUATION,
    "SETCONTCTRMANYX": IRType.SET_CONTINUATION,
    "SETEXITALT": IRType.SET_CONTINUATION,

    # cont_stack - Continuation arguments
    "SETCONTARGS_N": IRType.SET_CONTINUATION,
    "SETCONTVARARGS": IRType.SET_CONTINUATION,
    "SETNUMVARARGS": IRType.SET_CONTINUATION,
}
