"""
Dictionary Operations

This module contains mappings for:
- Dictionary get/set/delete operations
- Dictionary iteration (next/prev/min/max)
- Prefix dictionary operations
- Subdictionary operations
- Dictionary with builder variants
"""

from ..ir_types import IRType

DICT_OPS_MAPPINGS = {
    # ========== Dictionary Operations ==========
    "DICTGET": IRType.DICT_GET,
    "DICTIGET": IRType.DICT_GET,
    "DICTUGET": IRType.DICT_GET,
    "DICTGETREF": IRType.DICT_GET,
    "DICTIGETREF": IRType.DICT_GET,
    "DICTUGETREF": IRType.DICT_GET,

    "DICTSET": IRType.DICT_SET,
    "DICTISET": IRType.DICT_SET,
    "DICTUSET": IRType.DICT_SET,
    "DICTSETREF": IRType.DICT_SET,
    "DICTISETREF": IRType.DICT_SET,
    "DICTUSETREF": IRType.DICT_SET,

    "DICTDEL": IRType.DICT_DELETE,
    "DICTIDEL": IRType.DICT_DELETE,
    "DICTUDEL": IRType.DICT_DELETE,

    "DICTNEXT": IRType.DICT_ITERATE,
    "DICTPREV": IRType.DICT_ITERATE,
    "DICTINEXT": IRType.DICT_ITERATE,
    "DICTIPREV": IRType.DICT_ITERATE,
    "DICTUNEXT": IRType.DICT_ITERATE,
    "DICTUPREV": IRType.DICT_ITERATE,

    # Dictionary special operations
    "LDDICT": IRType.DICT_LOAD,
    "LDDICTS": IRType.DICT_LOAD,
    "STDICT": IRType.DICT_STORE,
    "SKIPDICT": IRType.DICT_LOAD,
    "DICTEMPTY": IRType.DICT_EMPTY,
    "DICTGETOPTREF": IRType.DICT_GET_OPT,
    "DICTIGETOPTREF": IRType.DICT_GET_OPT,
    "DICTUGETOPTREF": IRType.DICT_GET_OPT,

    # Dictionary add/replace/setget operations
    "DICTADD": IRType.DICT_SET,
    "DICTIADD": IRType.DICT_SET,
    "DICTUADD": IRType.DICT_SET,
    "DICTADDREF": IRType.DICT_SET,
    "DICTIADDREF": IRType.DICT_SET,
    "DICTUADDREF": IRType.DICT_SET,
    "DICTREPLACE": IRType.DICT_SET,
    "DICTIREPLACE": IRType.DICT_SET,
    "DICTUREPLACE": IRType.DICT_SET,
    "DICTREPLACEREF": IRType.DICT_SET,
    "DICTIREPLACEREF": IRType.DICT_SET,
    "DICTUREPLACEREF": IRType.DICT_SET,
    "DICTSETGET": IRType.DICT_SET,
    "DICTISETGET": IRType.DICT_SET,
    "DICTUSETGET": IRType.DICT_SET,
    "DICTSETGETREF": IRType.DICT_SET,
    "DICTISETGETREF": IRType.DICT_SET,
    "DICTUSETGETREF": IRType.DICT_SET,
    "DICTDELGET": IRType.DICT_DELETE,
    "DICTIDELGET": IRType.DICT_DELETE,
    "DICTUDELGET": IRType.DICT_DELETE,
    "DICTDELGETREF": IRType.DICT_DELETE,
    "DICTIDELGETREF": IRType.DICT_DELETE,
    "DICTUDELGETREF": IRType.DICT_DELETE,

    # Dictionary get+exec/jmp operations
    "DICTIGETEXEC": IRType.CALL_INDIRECT,
    "DICTUGETEXEC": IRType.CALL_INDIRECT,
    "DICTGETEXEC": IRType.CALL_INDIRECT,
    "DICTIGETJMP": IRType.UNCONDITIONAL_JUMP,
    "DICTUGETJMP": IRType.UNCONDITIONAL_JUMP,
    "DICTGETJMP": IRType.UNCONDITIONAL_JUMP,
    "DICTIGETEXECZ": IRType.CALL_INDIRECT,
    "DICTUGETEXECZ": IRType.CALL_INDIRECT,
    "DICTGETEXECZ": IRType.CALL_INDIRECT,
    "DICTIGETJMPZ": IRType.CONDITIONAL_JUMP,
    "DICTUGETJMPZ": IRType.CONDITIONAL_JUMP,
    "DICTGETJMPZ": IRType.CONDITIONAL_JUMP,

    # Dictionary min/max operations
    "DICTREMMINREF": IRType.DICT_DELETE,
    "DICTREMMAXREF": IRType.DICT_DELETE,
    "DICTIREMMINREF": IRType.DICT_DELETE,
    "DICTIREMMAXREF": IRType.DICT_DELETE,
    "DICTUREMMINREF": IRType.DICT_DELETE,
    "DICTUREMMAXREF": IRType.DICT_DELETE,

    # Prefix dictionary operations
    "PFXDICTGET": IRType.DICT_GET,
    "PFXDICTSET": IRType.DICT_SET,
    "PFXDICTREPLACE": IRType.DICT_SET,
    "PFXDICTADD": IRType.DICT_SET,
    "PFXDICTDEL": IRType.DICT_DELETE,
    "PFXDICTCONSTGETJMP": IRType.CONDITIONAL_JUMP,
    "PFXDICTGETJMP": IRType.CONDITIONAL_JUMP,
    "PFXDICTGETEXEC": IRType.CALL_INDIRECT,
    "PFXDICTSWITCH": IRType.CONDITIONAL_BRANCH,
    "PFXDICTGETQ": IRType.DICT_GET,

    # Subdictionary operations
    "SUBDICTGET": IRType.DICT_GET,
    "SUBDICTIGET": IRType.DICT_GET,
    "SUBDICTUGET": IRType.DICT_GET,
    "SUBDICTGETREF": IRType.DICT_GET,
    "SUBDICTIGETREF": IRType.DICT_GET,
    "SUBDICTUGETREF": IRType.DICT_GET,
    "SUBDICTRPGET": IRType.DICT_GET,
    "SUBDICTIRPGET": IRType.DICT_GET,
    "SUBDICTURPGET": IRType.DICT_GET,

    # Dict *B variants (with builder)
    "DICTADDB": IRType.DICT_SET,
    "DICTIADDB": IRType.DICT_SET,
    "DICTUADDB": IRType.DICT_SET,
    "DICTSETB": IRType.DICT_SET,
    "DICTISETB": IRType.DICT_SET,
    "DICTUSETB": IRType.DICT_SET,
    "DICTREPLACEB": IRType.DICT_SET,
    "DICTIREPLACEB": IRType.DICT_SET,
    "DICTUREPLACEB": IRType.DICT_SET,

    # Dict *GET variants (get and modify)
    "DICTADDGET": IRType.DICT_GET,
    "DICTIADDGET": IRType.DICT_GET,
    "DICTUADDGET": IRType.DICT_GET,
    "DICTADDGETB": IRType.DICT_GET,
    "DICTIADDGETB": IRType.DICT_GET,
    "DICTUADDGETB": IRType.DICT_GET,
    "DICTADDGETREF": IRType.DICT_GET,
    "DICTIADDGETREF": IRType.DICT_GET,
    "DICTUADDGETREF": IRType.DICT_GET,
    "DICTREPLACEGET": IRType.DICT_GET,
    "DICTIREPLACEGET": IRType.DICT_GET,
    "DICTUREPLACEGET": IRType.DICT_GET,
    "DICTREPLACEGETB": IRType.DICT_GET,
    "DICTIREPLACEGETB": IRType.DICT_GET,
    "DICTUREPLACEGETB": IRType.DICT_GET,
    "DICTREPLACEGETREF": IRType.DICT_GET,
    "DICTIREPLACEGETREF": IRType.DICT_GET,
    "DICTUREPLACEGETREF": IRType.DICT_GET,
    "DICTISETGETB": IRType.DICT_GET,
    "DICTUSETGETB": IRType.DICT_GET,
    "DICTSETGETB": IRType.DICT_GET,
    "DICTISETGETOPTREF": IRType.DICT_GET,
    "DICTUSETGETOPTREF": IRType.DICT_GET,
    "DICTSETGETOPTREF": IRType.DICT_GET,

    # Dict navigation (next/prev)
    "DICTGETNEXT": IRType.DICT_GET,
    "DICTIGETNEXT": IRType.DICT_GET,
    "DICTUGETNEXT": IRType.DICT_GET,
    "DICTGETNEXTEQ": IRType.DICT_GET,
    "DICTIGETNEXTEQ": IRType.DICT_GET,
    "DICTUGETNEXTEQ": IRType.DICT_GET,
    "DICTGETPREV": IRType.DICT_GET,
    "DICTIGETPREV": IRType.DICT_GET,
    "DICTUGETPREV": IRType.DICT_GET,
    "DICTGETPREVEQ": IRType.DICT_GET,
    "DICTIGETPREVEQ": IRType.DICT_GET,
    "DICTUGETPREVEQ": IRType.DICT_GET,
    "DICTMIN": IRType.DICT_GET,
    "DICTIMIN": IRType.DICT_GET,
    "DICTUMIN": IRType.DICT_GET,
    "DICTMAX": IRType.DICT_GET,
    "DICTIMAX": IRType.DICT_GET,
    "DICTUMAX": IRType.DICT_GET,
    "DICTMINREF": IRType.DICT_GET,
    "DICTIMINREF": IRType.DICT_GET,
    "DICTUMINREF": IRType.DICT_GET,
    "DICTMAXREF": IRType.DICT_GET,
    "DICTIMAXREF": IRType.DICT_GET,
    "DICTUMAXREF": IRType.DICT_GET,
    "DICTREMMIN": IRType.DICT_DELETE,
    "DICTIREMMIN": IRType.DICT_DELETE,
    "DICTUREMMIN": IRType.DICT_DELETE,
    "DICTREMMAX": IRType.DICT_DELETE,
    "DICTIREMMAX": IRType.DICT_DELETE,
    "DICTUREMMAX": IRType.DICT_DELETE,

    # CALLDICT - dynamic method dispatch (security-critical)
    "CALLDICT": IRType.CALL_INDIRECT,
    "CALLDICT_LONG": IRType.CALL_INDIRECT,
    "CALLXARGS_1": IRType.CALL_INDIRECT,

    # Dict push const and quiet variants
    "DICTPUSHCONST": IRType.DICT_GET,
    "LDDICTQ": IRType.DICT_LOAD,
    "PLDDICT": IRType.DICT_LOAD,
    "PLDDICTQ": IRType.DICT_LOAD,
    "PLDDICTS": IRType.DICT_LOAD,
}
