"""
Miscellaneous Operations: Crypto, App-level, Tuple, Const, Debug operations.
"""
from ..ir_types import IRType

CRYPTO_MAPPINGS = {
    # ========== Cryptographic Operations ==========
    "HASHCU": IRType.HASH_CELL,
    "HASHSU": IRType.HASH_SLICE,
    "SHA256U": IRType.SHA256,
    "CHKSIGNU": IRType.CHECK_SIGNATURE,
    "CHKSIGNS": IRType.CHECK_SIGNATURE,

    "HASHEXT_SHA256": IRType.HASH_EXT_SHA256,
    "HASHEXT_SHA512": IRType.HASH_EXT_SHA512,
    "HASHEXT_BLAKE2B": IRType.HASH_EXT_BLAKE2B,
    "HASHEXT_KECCAK256": IRType.HASH_EXT_KECCAK256,
    "HASHEXT_KECCAK512": IRType.HASH_EXT_KECCAK512,

    "HASHEXTR_SHA256": IRType.HASH_EXT_SHA256,
    "HASHEXTR_SHA512": IRType.HASH_EXT_SHA512,
    "HASHEXTR_BLAKE2B": IRType.HASH_EXT_BLAKE2B,
    "HASHEXTR_KECCAK256": IRType.HASH_EXT_KECCAK256,
    "HASHEXTR_KECCAK512": IRType.HASH_EXT_KECCAK512,

    "HASHEXTA_SHA256": IRType.HASH_EXT_SHA256,
    "HASHEXTA_SHA512": IRType.HASH_EXT_SHA512,
    "HASHEXTA_BLAKE2B": IRType.HASH_EXT_BLAKE2B,
    "HASHEXTA_KECCAK256": IRType.HASH_EXT_KECCAK256,
    "HASHEXTA_KECCAK512": IRType.HASH_EXT_KECCAK512,

    "HASHEXTAR_SHA256": IRType.HASH_EXT_SHA256,
    "HASHEXTAR_SHA512": IRType.HASH_EXT_SHA512,
    "HASHEXTAR_BLAKE2B": IRType.HASH_EXT_BLAKE2B,
    "HASHEXTAR_KECCAK256": IRType.HASH_EXT_KECCAK256,
    "HASHEXTAR_KECCAK512": IRType.HASH_EXT_KECCAK512,

    # Generic HASHEXT forms with runtime algorithm selector argument.
    "HASHEXT": IRType.HASH_EXT_SHA256,
    "HASHEXTR": IRType.HASH_EXT_SHA256,
    "HASHEXTA": IRType.HASH_EXT_SHA256,
    "HASHEXTAR": IRType.HASH_EXT_SHA256,

    "HASHBU": IRType.HASH_CELL,

    # Advanced Crypto Operations
    # secp256k1 recovery
    "ECRECOVER": IRType.CRYPTO_ECRECOVER,

    # P-256 (secp256r1)
    "P256_CHKSIGNU": IRType.CRYPTO_P256_CHKSIG,
    "P256_CHKSIGNS": IRType.CRYPTO_P256_CHKSIG,

    # Rist255 curve operations
    "RIST255_FROMHASH": IRType.CRYPTO_RIST255_OP,
    "RIST255_VALIDATE": IRType.CRYPTO_RIST255_OP,
    "RIST255_ADD": IRType.CRYPTO_RIST255_OP,
    "RIST255_SUB": IRType.CRYPTO_RIST255_OP,
    "RIST255_MUL": IRType.CRYPTO_RIST255_OP,
    "RIST255_MULBASE": IRType.CRYPTO_RIST255_OP,
    "RIST255_PUSHL": IRType.PUSH_INT,
    "RIST255_QADD": IRType.CRYPTO_RIST255_OP,
    "RIST255_QMUL": IRType.CRYPTO_RIST255_OP,
    "RIST255_QMULBASE": IRType.CRYPTO_RIST255_OP,
    "RIST255_QSUB": IRType.CRYPTO_RIST255_OP,
    "RIST255_QVALIDATE": IRType.CRYPTO_RIST255_OP,
    "SECP256K1_XONLY_PUBKEY_TWEAK_ADD": IRType.CRYPTO_ECRECOVER,

    # BLS12-381 G1 operations
    "BLS_G1_ADD": IRType.CRYPTO_BLS_G1_ADD,
    "BLS_G1_SUB": IRType.CRYPTO_BLS_G1_ADD,
    "BLS_G1_NEG": IRType.CRYPTO_BLS_G1_ADD,
    "BLS_G1_MUL": IRType.CRYPTO_BLS_G1_MUL,
    "BLS_G1_MULTIEXP": IRType.CRYPTO_BLS_G1_MUL,
    "BLS_G1_ZERO": IRType.CRYPTO_BLS_G1_ADD,
    "BLS_G1_ISZERO": IRType.CRYPTO_BLS_G1_ADD,
    "BLS_G1_INGROUP": IRType.CRYPTO_BLS_G1_ADD,
    "BLS_G1_FROMHASH": IRType.CRYPTO_BLS_G1_ADD,

    # BLS12-381 G2 operations
    "BLS_G2_ADD": IRType.CRYPTO_BLS_G1_ADD,
    "BLS_G2_SUB": IRType.CRYPTO_BLS_G1_ADD,
    "BLS_G2_NEG": IRType.CRYPTO_BLS_G1_ADD,
    "BLS_G2_MUL": IRType.CRYPTO_BLS_G1_MUL,
    "BLS_G2_MULTIEXP": IRType.CRYPTO_BLS_G1_MUL,
    "BLS_G2_ZERO": IRType.CRYPTO_BLS_G1_ADD,
    "BLS_G2_ISZERO": IRType.CRYPTO_BLS_G1_ADD,
    "BLS_G2_INGROUP": IRType.CRYPTO_BLS_G1_ADD,
    "BLS_G2_FROMHASH": IRType.CRYPTO_BLS_G1_ADD,

    # BLS12-381 pairing operations
    "BLS_PAIRING": IRType.CRYPTO_BLS_PAIRING,
    "BLS_PUSHR": IRType.PUSH_INT,
    "BLS_MAP_TO_G1": IRType.CRYPTO_BLS_G1_ADD,
    "BLS_MAP_TO_G2": IRType.CRYPTO_BLS_G1_ADD,

    # Additional BLS operations
    "BLS_VERIFY": IRType.CRYPTO_BLS_PAIRING,
    "BLS_AGGREGATE": IRType.CRYPTO_BLS_G1_ADD,
    "BLS_FASTAGGREGATEVERIFY": IRType.CRYPTO_BLS_PAIRING,
    "BLS_AGGREGATEVERIFY": IRType.CRYPTO_BLS_PAIRING,
}

APP_GAS_MAPPINGS = {
    # ========== Application-Level: Gas ==========
    "ACCEPT": IRType.ACCEPT_GAS,
    "SETGASLIMIT": IRType.SET_GAS_LIMIT,
    "GASCONSUMED": IRType.GET_GAS_CONSUMED,
    "COMMIT": IRType.COMMIT_STATE,
}

APP_ACTION_MAPPINGS = {
    # ========== Application-Level: Actions ==========
    "SENDRAWMSG": IRType.SEND_MESSAGE,
    "SENDMSG": IRType.SEND_MESSAGE,
    "RAWRESERVE": IRType.RESERVE_CURRENCY,
    "RAWRESERVEX": IRType.RESERVE_CURRENCY,
    "SETCODE": IRType.SET_CODE,
    "SETLIBCODE": IRType.SET_LIB_CODE,
    "CHANGELIB": IRType.SET_LIB_CODE,
}

APP_ADDRESS_MAPPINGS = {
    # ========== Application-Level: Address ==========
    "LDMSGADDR": IRType.LOAD_MSG_ADDRESS,
    "LDMSGADDRQ": IRType.LOAD_MSG_ADDRESS,
    "INMSG_SRC": IRType.LOAD_MSG_ADDRESS,
    "PARSEMSGADDR": IRType.PARSE_MSG_ADDRESS,
    "PARSEMSGADDRQ": IRType.PARSE_MSG_ADDRESS,
    "REWRITESTDADDR": IRType.REWRITE_ADDRESS,
    "REWRITESTDADDRQ": IRType.REWRITE_ADDRESS,
    "REWRITEVARADDR": IRType.REWRITE_ADDRESS,
    "REWRITEVARADDRQ": IRType.REWRITE_ADDRESS,
    "LDSTDADDR": IRType.LOAD_MSG_ADDRESS,
    "LDSTDADDRQ": IRType.LOAD_MSG_ADDRESS,
    "LDOPTSTDADDR": IRType.LOAD_MSG_ADDRESS,
    "LDOPTSTDADDRQ": IRType.LOAD_MSG_ADDRESS,
    "STSTDADDR": IRType.STORE_UINT,
    "STSTDADDRQ": IRType.STORE_UINT,
    "STOPTSTDADDR": IRType.STORE_UINT,
    "STOPTSTDADDRQ": IRType.STORE_UINT,
}

APP_CONFIG_MAPPINGS = {
    # ========== Application-Level: Config/Blockchain ==========
    "GETPARAM": IRType.GET_BLOCKCHAIN_PARAM,
    "CONFIGDICT": IRType.GET_CONFIG_DICT,
    "CONFIGPARAM": IRType.GET_CONFIG_PARAM,
    "CONFIGOPTPARAM": IRType.GET_CONFIG_PARAM,
    "PREVMCBLOCKS": IRType.GET_BLOCK_INFO,
    "PREVKEYBLOCK": IRType.GET_BLOCK_INFO,
    "GLOBALID": IRType.GET_GLOBAL_ID,
    "GETGASFEE": IRType.GET_GAS_FEE,
    "GETGASFEESIMPLE": IRType.GET_GAS_FEE,
    "GETSTORAGEFEE": IRType.GET_STORAGE_FEE,
    "GETFORWARDFEE": IRType.GET_FORWARD_FEE,
    "GETFORWARDFEESIMPLE": IRType.GET_FORWARD_FEE,
    "GETORIGINALFWDFEE": IRType.GET_FORWARD_FEE,
    "GETPRECOMPILEDGAS": IRType.GET_GAS_FEE,
    "BLOCKLT": IRType.GET_BLOCK_INFO,
    "GETPARAMLONG": IRType.GET_CONFIG_PARAM,
    "GETPARAMLONG2": IRType.GET_CONFIG_PARAM,
    # GETPARAM aliases in cp0
    "NOW": IRType.GET_BLOCKCHAIN_PARAM,
    "LTIME": IRType.GET_BLOCKCHAIN_PARAM,
    "MYCODE": IRType.GET_BLOCKCHAIN_PARAM,
    "INCOMINGVALUE": IRType.GET_BLOCKCHAIN_PARAM,
    "PREVBLOCKSINFOTUPLE": IRType.GET_BLOCKCHAIN_PARAM,
    "DUEPAYMENT": IRType.GET_STORAGE_FEE,
    "STORAGEFEES": IRType.GET_STORAGE_FEE,
    "INMSGPARAM": IRType.GET_CONFIG_PARAM,
    # INMSGPARAM aliases in cp0
    "INMSGPARAMS": IRType.GET_CONFIG_PARAM,
    "INMSG_BOUNCE": IRType.GET_CONFIG_PARAM,
    "INMSG_BOUNCED": IRType.GET_CONFIG_PARAM,
    "INMSG_FWDFEE": IRType.GET_CONFIG_PARAM,
    "INMSG_LT": IRType.GET_CONFIG_PARAM,
    "INMSG_UTIME": IRType.GET_CONFIG_PARAM,
    "INMSG_ORIGVALUE": IRType.GET_CONFIG_PARAM,
    "INMSG_VALUE": IRType.GET_CONFIG_PARAM,
    "INMSG_VALUEEXTRA": IRType.GET_CONFIG_PARAM,
    "INMSG_STATEINIT": IRType.GET_CONFIG_PARAM,
    "PREVMCBLOCKS_100": IRType.GET_CONFIG_PARAM,
    "CONFIGROOT": IRType.GET_CONFIG_DICT,
    "UNPACKEDCONFIGTUPLE": IRType.GET_CONFIG_PARAM,
}

APP_CURRENCY_MAPPINGS = {
    # ========== Application-Level: Currency ==========
    "LDGRAMS": IRType.LOAD_GRAMS,
    "LDVARINT16": IRType.LOAD_VARINT,
    "LDVARINT32": IRType.LOAD_VARINT,
    "LDVARUINT32": IRType.LOAD_VARINT,
    "STGRAMS": IRType.STORE_GRAMS,
    "STVARINT16": IRType.STORE_VARINT,
    "STVARINT32": IRType.STORE_VARINT,
    "STVARUINT32": IRType.STORE_VARINT,
}

APP_GLOBAL_VAR_MAPPINGS = {
    # ========== Application-Level: Global Variables ==========
    "GETGLOBVAR": IRType.GET_GLOBAL_VAR,
    "GETGLOB": IRType.GET_GLOBAL_VAR,
    "SETGLOBVAR": IRType.SET_GLOBAL_VAR,
    "SETGLOB": IRType.SET_GLOBAL_VAR,
    "SETRAND": IRType.SET_GLOBAL_VAR,
    "RANDSEED": IRType.GET_GLOBAL_VAR,
}

APP_MISC_MAPPINGS = {
    # ========== Application-Level: Misc ==========
    "CDATASIZE": IRType.GET_CELL_DATA_SIZE,
    "CDATASIZEQ": IRType.GET_CELL_DATA_SIZE,
    "SDATASIZE": IRType.GET_SLICE_DATA_SIZE,
    "SDATASIZEQ": IRType.GET_SLICE_DATA_SIZE,

    # Balance and Address Operations (Security-related)
    "BALANCE": IRType.LOAD_STORAGE,
    "GETEXTRABALANCE": IRType.LOAD_STORAGE,
    "MYADDR": IRType.LOAD_STORAGE,
}

TUPLE_MAPPINGS = {
    # ========== Tuple Operations ==========
    "TUPLE": IRType.TUPLE_CREATE,
    "TUPLEVAR": IRType.TUPLE_CREATE,
    "NULL": IRType.TUPLE_NULL,
    "ISNULL": IRType.TUPLE_IS_NULL,
    "INDEX": IRType.TUPLE_INDEX,
    "INDEXQ": IRType.TUPLE_INDEX,
    "INDEXVAR": IRType.TUPLE_INDEX,
    "INDEXVARQ": IRType.TUPLE_INDEX,
    "SETINDEX": IRType.TUPLE_SET,
    "SETINDEXQ": IRType.TUPLE_SET,
    "SETINDEXVAR": IRType.TUPLE_SET,
    "SETINDEXVARQ": IRType.TUPLE_SET,
    "TLEN": IRType.TUPLE_LENGTH,
    "QTLEN": IRType.TUPLE_LENGTH,
    "ISTUPLE": IRType.TUPLE_IS_TUPLE,
    "UNTUPLE": IRType.TUPLE_UNPACK,
    "UNTUPLEVAR": IRType.TUPLE_UNPACK,
    "UNPACKFIRST": IRType.TUPLE_UNPACK_FIRST,
    "UNPACKFIRSTVAR": IRType.TUPLE_UNPACK_FIRST,
    "EXPLODE": IRType.TUPLE_EXPLODE,
    "EXPLODEVAR": IRType.TUPLE_EXPLODE,
    "LAST": IRType.TUPLE_LAST,
    "TPUSH": IRType.TUPLE_OPERATIONS,
    "TPOP": IRType.TUPLE_OPERATIONS,
    # Additional tuple operations
    "NULLSWAPIF": IRType.TUPLE_NULL,
    "NULLSWAPIFNOT": IRType.TUPLE_NULL,
    "NULLROTRIF": IRType.TUPLE_NULL,
    "NULLROTRIFNOT": IRType.TUPLE_NULL,
    "NULLSWAPIF2": IRType.TUPLE_NULL,
    "NULLSWAPIFNOT2": IRType.TUPLE_NULL,
    "NULLROTRIF2": IRType.TUPLE_NULL,
    "NULLROTRIFNOT2": IRType.TUPLE_NULL,
    "INDEX2": IRType.TUPLE_INDEX,
    "INDEX3": IRType.TUPLE_INDEX,
}

CONST_MAPPINGS = {
    # ========== Const Operations ==========
    "PUSHNULL": IRType.TUPLE_NULL,
    "PUSHINT": IRType.PUSH_INT,
    "PUSHINT_4": IRType.PUSH_INT,
    "PUSHINT_8": IRType.PUSH_INT,
    "PUSHINT_16": IRType.PUSH_INT,
    "PUSHINT_LONG": IRType.PUSH_INT,
    "PUSHPOW2": IRType.PUSH_INT,
    "PUSHPOW2DEC": IRType.PUSH_INT,
    "PUSHNEGPOW2": IRType.PUSH_INT,
    "PUSHNAN": IRType.PUSH_NAN,
    "PUSHREF": IRType.PUSH_REF,
    "PUSHREFSLICE": IRType.PUSH_SLICE,
    "PUSHREFCONT": IRType.PUSH_CONT,
    "PUSHSLICE": IRType.PUSH_SLICE,
    "PUSHSLICE_REFS": IRType.PUSH_SLICE,
    "PUSHSLICE_LONG": IRType.PUSH_SLICE,
}

DEBUG_MAPPINGS = {
    # ========== Debug Operations ==========
    "DEBUG": IRType.DEBUG_PRINT,
    "DEBUGMARK": IRType.DEBUG_PRINT,
    "DEBUGSTR": IRType.DEBUG_PRINT,
    "DEBUG_1": IRType.DEBUG_PRINT,
    "DEBUG_2": IRType.DEBUG_PRINT,
    "DUMP": IRType.DEBUG_PRINT,
    "DUMPSTK": IRType.DEBUG_PRINT,
    "STRDUMP": IRType.DEBUG_PRINT,
}

CODEPAGE_MAPPINGS = {
    # ========== Codepage Operations ==========
    "SETCP": IRType.NOP,
    "SETCP_SHORT": IRType.NOP,
    "SETCPX": IRType.NOP,
    "SETCP_SPECIAL": IRType.NOP,
}

# Combined misc operations
MISC_OPS_MAPPINGS = {
    **CRYPTO_MAPPINGS,
    **APP_GAS_MAPPINGS,
    **APP_ACTION_MAPPINGS,
    **APP_ADDRESS_MAPPINGS,
    **APP_CONFIG_MAPPINGS,
    **APP_CURRENCY_MAPPINGS,
    **APP_GLOBAL_VAR_MAPPINGS,
    **APP_MISC_MAPPINGS,
    **TUPLE_MAPPINGS,
    **CONST_MAPPINGS,
    **DEBUG_MAPPINGS,
    **CODEPAGE_MAPPINGS,
}
