"""
Solver IR exporters.

This module currently provides a basic SMT-LIB v2 exporter suitable for:
- smoke-testing solver lowering correctness
- feeding into an SMT backend in future work packages
"""
from __future__ import annotations

from typing import Dict

from .types import SolverModule


_SMT_SORT_MAP: Dict[str, str] = {
    "Bool": "Bool",
    "Int": "Int",
    # Domain-specific aliases currently lowered to Int.
    "ContRef": "Int",
    "MethodId": "Int",
}


class SMTLibExporter:
    """Export SolverModule into a minimal SMT-LIB v2 script."""

    def export(self, module: SolverModule, include_check_sat: bool = True) -> str:
        lines = [
            "; Generated by tasmscan Solver IR exporter",
            "; source=solver_ir",
        ]

        for name in sorted(module.symbols):
            sym = module.symbols[name]
            sort = _SMT_SORT_MAP.get(sym.sort, "Int")
            lines.append(f"(declare-fun {sym.name} () {sort})")

        for constraint in module.constraints:
            if constraint.kind != "assert":
                continue
            lines.append(f"(assert {constraint.expression})")

        if include_check_sat:
            lines.append("(check-sat)")

        return "\n".join(lines) + "\n"

